### ISSUE TITLE
按照推荐配置的yml 之前可以正常部署文档系统，最近一段时间文档系统无法拉取最新代码

### ISSUE THREAD

**Issue by singsad** [docsifyjs/docs-zh#36]
我的项目托管在gitlab上，yml配置参考文档。前段时间可以正常部署，文档系统可以随时更新。
最近一段时间在CI/CD 成功之后，文档系统也没有拿到最新的数据。
想请教一下问题可能出在哪里
我的几个项目的文档系统都无法更新

**Comment by sy-records** [comment]
文件发出来

**Comment by singsad** [comment]
pages:
  stage: deploy
  script:
  - echo 'public'
  - cp -r docs/. public
  artifacts:
    paths:
    - public
  only:
  - test
  - feature/SPPMS-13026/siqi-fbs-portal
  - feature/SPFBS-1078/zhi-docs-update

  when: always

**Comment by singsad** [comment]
```
pages:
  stage: deploy
  script:
  - echo 'public'
  - cp -r docs/. public
  artifacts:
    paths:
    - public
  only:
  - test
  - feature/SPPMS-13026/siqi-fbs-portal
  - feature/SPFBS-1078/zhi-docs-update

  # TODO 匹配自动触发配置
  when: always

```
